FROM alpine:3.12.0

RUN apk update && apk add --no-cache --upgrade bash
RUN apk add openrc
RUN apk add telegraf --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache

RUN wget https://dl.grafana.com/oss/release/grafana-7.1.5.linux-amd64.tar.gz \
&& tar -zxf grafana-7.1.5.linux-amd64.tar.gz \
&& mv grafana-7.1.5 grafana \
&& rm -r grafana-7.1.5.linux-amd64.tar.gz
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main libc6-compat

COPY ./grafana.db ./grafana/data/
COPY start.sh /start.sh

RUN mkdir -p /etc/telegraf
COPY ./telegraf.conf /etc/telegraf/telegraf.conf

COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 3000

CMD ./start.sh