#Source: https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
#Change name
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  ports:
  - port: 3306
  selector:
    app: ft_services
    tier: mysql
  clusterIP: None

---

apiVersion: v1
kind: persistentVolumeClaim
metadata:
    name: mysql-pv-claim
    labels:
        app: ft_services
spec:
    accessModels:
    - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
---

# for versions before 1.9.0 use apps/v1beta2
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: custom-mysql:1.11
        imagePullPolicy: Never
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueForm:
            secretKeyRef:
               name: mysql-pass
               key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
